# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_auto_20200630_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, null=True)),
                ('section', models.CharField(max_length=64, null=True)),
                ('object', models.CharField(max_length=128, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 30, 1, 36, 41, 746537))),
                ('params', models.TextField()),
                ('user', models.ForeignKey(help_text='Object of action', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
