# Generated by Django 2.2.4 on 2020-06-30 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 14, 24, 14, 606378)),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='Object of action', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
    ]
