# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20200630_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 21, 6, 13, 324760)),
        ),
    ]
