# Generated by Django 2.2.4 on 2020-07-01 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20200630_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 10, 34, 2, 354584)),
        ),
    ]
