# Generated by Django 2.2.4 on 2020-07-01 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_auto_20200701_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 11, 13, 26, 167458)),
        ),
    ]
