# Generated by Django 3.0.5 on 2020-06-26 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_user',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('pin', models.BinaryField()),
                ('status', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('key', models.CharField(max_length=16)),
                ('delete_time', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 3, 22, 44, 626431))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('salt', models.BinaryField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('skin', models.ImageField(upload_to='')),
                ('birthday', models.DateField()),
            ],
        ),
    ]
