# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200627_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 23, 28, 54, 759261)),
        ),
    ]
