# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200628_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 23, 46, 23, 348957)),
        ),
    ]
