# Generated by Django 2.2.4 on 2020-06-30 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200630_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 14, 24, 14, 602378)),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='key',
            field=models.CharField(default='EIXUXbbcEPBtFToS', max_length=16),
        ),
    ]
