# Generated by Django 2.2.4 on 2020-06-30 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200630_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 15, 22, 59, 568995)),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='key',
            field=models.CharField(default='SfoaLeteDQGGTkan', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 15, 22, 59, 567994), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 15, 22, 59, 567994)),
        ),
    ]
