# Generated by Django 2.2.4 on 2020-06-30 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200630_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 15, 54, 32, 172245)),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='key',
            field=models.CharField(default='ELIyCxLUzfOGTIuC', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 15, 54, 32, 171245), null=True),
        ),
        migrations.CreateModel(
            name='user_updater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='gLyItUpKbQGpITvo', max_length=16)),
                ('change', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
