# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200630_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 6, 13, 312374)),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='key',
            field=models.CharField(default='aVMOBVEYkCvAZSLS', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 21, 6, 13, 310014), null=True),
        ),
        migrations.AlterField(
            model_name='user_updater',
            name='key',
            field=models.CharField(default='WselTkVEtmmXgWGI', max_length=16),
        ),
    ]
