# Generated by Django 2.2.4 on 2020-07-01 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200630_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 10, 34, 2, 349583)),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='key',
            field=models.CharField(default='reuUVIvtCYlFXRjl', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 1, 10, 34, 2, 348583), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg',
            field=models.DateField(default=datetime.date(2020, 7, 1)),
        ),
        migrations.AlterField(
            model_name='user_updater',
            name='key',
            field=models.CharField(default='gKwyvXMWcpCypzne', max_length=16),
        ),
    ]
