# Generated by Django 2.2.4 on 2020-07-01 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200701_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 11, 13, 26, 162458)),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='key',
            field=models.CharField(default='pPvOtASoyNRvLUQj', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 1, 11, 13, 26, 161458), null=True),
        ),
        migrations.AlterField(
            model_name='user_updater',
            name='key',
            field=models.CharField(default='lQoNfLHIAnTXaxyE', max_length=16),
        ),
    ]
