# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 38, 31, 166874)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 38, 31, 166874)),
        ),
        migrations.AlterField(
            model_name='skin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 38, 31, 166874)),
        ),
        migrations.AlterField(
            model_name='uploadurl',
            name='access',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 9, 38, 31, 166874)),
        ),
    ]
