# Generated by Django 2.2.4 on 2020-06-29 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200629_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadurl',
            old_name='access',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 19, 52, 8, 835567)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 19, 52, 8, 834567)),
        ),
        migrations.AlterField(
            model_name='skin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 19, 52, 8, 835567)),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 19, 52, 8, 834567)),
        ),
    ]
