# Generated by Django 2.2.4 on 2020-06-29 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200629_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadurl',
            name='to',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 21, 48, 19, 699278)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 21, 48, 19, 697278)),
        ),
        migrations.AlterField(
            model_name='skin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 21, 48, 19, 698278)),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 21, 48, 19, 698278)),
        ),
    ]
