# Generated by Django 2.2.4 on 2020-06-29 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20200629_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(default='_', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skin',
            name='hash',
            field=models.CharField(default='somestring', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='hash',
            field=models.CharField(default='somestring', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 23, 33, 676191)),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 23, 33, 674190)),
        ),
        migrations.AlterField(
            model_name='skin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 23, 33, 675190)),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 22, 23, 33, 675190)),
        ),
    ]
